name: xylophone
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  audioplayers: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/1.wav
    - assets/2.wav
    - assets/3.wav
    - assets/4.wav
    - assets/5.wav
    - assets/6.wav
    - assets/7.wav
    - assets/8.wav
